# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-15 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171015_1022'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=b'avatars'),
        ),
    ]
