# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_auto_20171016_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_id',
            field=models.IntegerField(default=0),
        ),
    ]
