# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0007_auto_20171016_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-blog_id',), 'verbose_name': '\u0411\u043b\u043e\u0433', 'verbose_name_plural': '\u0411\u043b\u043e\u0433\u0438'},
        ),
    ]
