# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 23:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_auto_20171016_2045'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('-updated_at',), 'verbose_name': '\u0411\u043b\u043e\u0433', 'verbose_name_plural': '\u0411\u043b\u043e\u0433\u0438'},
        ),
        migrations.RemoveField(
            model_name='blog',
            name='blog_id',
        ),
    ]
