# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 16:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_auto_20171015_2116'),
        ('post_app', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='blog_app.Blog'),
            preserve_default=False,
        ),
    ]
