# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0004_post_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='postId',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
