# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 17:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0007_auto_20171016_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='postId',
        ),
    ]
