# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_app', '0009_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='count',
        ),
    ]
