# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 20:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0005_auto_20171016_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
