# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0008_remove_comment_comment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_id',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
