# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment_app', '0009_comment_comment_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_id',
        ),
    ]
